import { StyleSheet } from 'react-native';

const problemDetailsStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingHorizontal: 20,
      paddingVertical: 30,
    },
    title: {
      fontSize: 22,
      fontWeight: 'bold',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 20,
    },
    problemsContainer: {
      backgroundColor: colors.cardBackground,
      borderRadius: 10,
      padding: 15,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
    },
    problemsText: {
      color: colors.text,
      fontSize: 16,
      textAlign: 'left',
      lineHeight: 24,
    },
    subtitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 10,
      textAlign: 'center',
    },
    descriptionInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      padding: 10,
      height: 80,
      marginBottom: 20,
      fontSize: 16,
      borderWidth: 1,
      borderColor: colors.border,
      textAlignVertical: 'top',
    },
    imagePreviewContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      marginBottom: 20,
    },
    imageContainer: {
      position: 'relative',
      marginRight: 10,
      marginBottom: 10,
    },
    imagePreview: {
      width: 80,
      height: 80,
      borderRadius: 8,
    },
    removeIcon: {
      position: 'absolute',
      top: -5,
      right: -5,
      backgroundColor: 'red',
      borderRadius: 12,
      padding: 2,
    },
    actionsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 20,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.buttonBackground,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
    },
    actionButtonText: {
      marginLeft: 8,
      fontSize: 14,
      color: colors.buttonText,
    },
    sendButton: {
      backgroundColor: colors.primary,
      paddingVertical: 15,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
    },
    sendButtonText: {
      color: colors.buttonText,
      fontSize: 16,
      fontWeight: 'bold',
    },
  });

export default problemDetailsStyles;
